# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
title: Portfolio
logo: "/assets/images/integral.png"
subtitle: "Version 2.0"
email: mohalzeqri@gmail.com
description: >-
  Dedicated to showcasing my expertise in mathematics, computer science, and quantitative research. 
  Explore projects, experience, and insights into solving complex problems through mathematical methodologies.
github_username: M-Alzeqri
minimal_mistakes_skin: contrast
search: true

# Kramdown Configuration for MathJax
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
  hard_wrap: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Pagination using jekyll-paginate-v2
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - Page :num'
  trail:
    before: 2
    after: 2

# Output settings
permalink: /:categories/:title/
timezone: "America/Toronto" # Set your timezone, e.g., "America/Toronto"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-lunr-js-search # If using Lunr.js for search

minimal_mistakes:
  math:
    enabled: true
    engine: mathjax
    config: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
  
author:
  name   : "Mohammed Al-zeqri"
  avatar : "/assets/images/profile-pic.jpg"
  bio    : "Devoted to crafting strategic solutions through the rigorous application of mathematical methodologies."
  location : "Toronto, CA"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mohammed-al-zeqri/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mohammed-al-zeqri/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
