# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Jekyll Configuration for Minimal Mistakes Theme v4.26.2

# Site settings
title: -Portfolio
logo: "/assets/images/sigma.webp"
email: mohalzeqri@gmail.com
description: >-
  Dedicated to showcasing my expertise in mathematics, computer science, and quantitative research. 
  Explore projects, experience, and insights into solving complex problems through mathematical methodologies.

github_username: M-Alzeqri
minimal_mistakes_skin: contrast
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 3 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Minimal Mistakes Wide Page
classes: wide

include:
  - _pages
  - cs
  - math
  - quant

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Mohammed Al-zeqri"
  avatar : "/assets/images/profile-pic.jpg"
  bio    : "Mathematician by training, problem-solver by passion.."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://m-alzeqri.github.io/portfolio/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mohammed-al-zeqri/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/M-Alzeqri"
    - label: "Contact"
      icon: "fas fa-fw fa-envelope"
      url: "https://m-alzeqri.github.io/portfolio/contact/"
    - label: "Kaggle"
      icon: "fas fa-fw fa-chart-line"
      url: "https://www.kaggle.com/settings"
    - label: "QuantConnect"
      icon: "fas fa-fw fa-network-wired"
      url: "https://www.quantconnect.com/terminal/#newUser/"
    - label: "LeetCode"
      icon: "fas fa-fw fa-code"
      url: "https://leetcode.com/u/mohalzeqri/"
    - label: "MathOverflow"
      icon: "fas fa-fw fa-calculator"
      url: "https://mathoverflow.net/users/550305/mohammed-al-zeqri"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mohammed-al-zeqri/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/M-Alzeqri"
    - label: "Contact"
      icon: "fas fa-fw fa-envelope"
      url: "/contact/"
    - label: "Kaggle"
      icon: "fas fa-fw fa-chart-line"
      url: "https://www.kaggle.com/settings"
    - label: "QuantConnect"
      icon: "fas fa-fw fa-network-wired"
      url: "https://www.quantconnect.com/terminal/#newUser/"
    - label: "LeetCode"
      icon: "fas fa-fw fa-code"
      url: "https://leetcode.com/u/mohalzeqri/"
    - label: "MathOverflow"
      icon: "fas fa-fw fa-calculator"
      url: "https://mathoverflow.net/users/550305/mohammed-al-zeqri"


defaults:
  # _posts
  - scope:
      path: ""
 #     type: posts
    values:
      layout: single
      classes: wide
 #     author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
  #    author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
