name: Jekyll Site CI

on:
  push:
    branches: [ master ]       # Use 'main' if that's your default branch
  pull_request:
    branches: [ master ]       # Use 'main' if that's your default branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04      # Temporarily specify 'ubuntu-22.04' for compatibility

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true      # Corrected input

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Build the site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages     # Deploy to 'gh-pages' branch
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
